In [1]:
import numpy as np

<h2 id="exercises">Exercises</h2>
<p>In your <code>numpy-pandas-visualization-exercises</code> repo, create a file named <code>numpy_exercises.py</code> for this exercise.</p>
<p>Use the following code for the questions below:


In [79]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there? (4)

In [6]:
len(a[a < 0])

4


2. How many positive numbers are there? (5)

In [82]:
a[a > 0]
a[a > 0].size

5

3. How many even positive numbers are there? (3)

In [83]:
(a[(a > 0) & (a % 2 == 0)]).size

3

4. If you were to add 3 to each data point, how many positive numbers would
   there be? (10)

In [84]:
a3 = a+3
a3[a3 > 0].size

10

5. If you squared each number, what would the new mean and standard deviation
   be? (mean = 74, std = 144.02)

In [17]:
a2 = a**2
a2.mean(), a2.std()

(74.0, 144.0243035046516)

6. A common statistical operation on a dataset is <strong>centering</strong>. This means to
   adjust the data such that the mean of the data is 0. This is done by
   subtracting the mean from each data point. Center the data set. See <a href="https://www.theanalysisfactor.com/centering-and-standardizing-predictors/">this link</a> for more on centering.

In [19]:
a - a.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

7. Calculate the z-score for each data point. Recall that the z-score is given
   by:
   
Z = $\frac{x - \mu}{\sigma}$

In [20]:
(a - a.mean())/a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. Copy the setup and exercise directions from <a href="https://gist.github.com/ryanorsinger/c4cf5a64ec33c014ff2e56951bc8a42d">More Numpy Practice</a> into your <code>numpy_exercises.py</code> and add your solutions.

### Setup 1

### Use python's built in functionality/operators to determine the following:

In [13]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list.

In [14]:
sum_of_a = sum(a)
sum_of_a

55

Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list.

In [15]:
min_of_a = min(a)
min_of_a

1

Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list.

In [16]:
max_of_a = max(a)
max_of_a

10

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list.

In [17]:
mean_of_a = sum(a)/len(a)
mean_of_a

5.5

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together.

In [18]:
product_of_a = 1
for el in a:
    product_of_a *= el
product_of_a

3628800

Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...].

In [20]:
squares_of_a = [el **2 for el in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers.

In [21]:
odds_in_a = [el for el in a if el % 2 == 1]
odds_in_a

[1, 3, 5, 7, 9]

Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [22]:
evens_in_a = [el for el in a if el % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
### Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [23]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b = np.array(b)

Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [24]:
sum_of_b = b.sum()
sum_of_b

33

Exercise 2 - refactor the following to use numpy. 

In [25]:
min_of_b = b.min()
min_of_b

3

Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [26]:
max_of_b = b.max()
max_of_b

8

Exercise 4 - refactor the following using numpy to find the mean of b

In [27]:
mean_of_b = b.mean()
mean_of_b

5.5

Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [28]:
product_of_b = np.product(b)
product_of_b

20160

Exercise 6 - refactor the following to use numpy to find the list of squares 

In [29]:
squares_of_b = np.square(b)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

Exercise 7 - refactor using numpy to determine the odds_in_b

In [30]:
odds_in_b = b[b%2==1]
odds_in_b

array([3, 5, 7])

Exercise 8 - refactor the following to use numpy to filter only the even numbers.

In [31]:
evens_in_b = b[b%2==0]
evens_in_b

array([4, 6, 8])

Exercise 9 - print out the shape of the array b.

In [32]:
np.shape(b)

(2, 3)

Exercise 10 - transpose the array b.

In [33]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [34]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [35]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Setup 3

In [36]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c = np.array(c)

 HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
Exercise 1 - Find the min, max, sum, and product of c. 

In [37]:
dict = {'min': c.min(),
        'max' : c.max(),
        'sum' : c.sum(),
        'product' : np.product(c)}
dict

{'min': 1, 'max': 9, 'sum': 45, 'product': 362880}

Exercise 2 - Determine the standard deviation of c.

In [38]:
c.std()

2.581988897471611

Exercise 3 - Determine the variance of c.

In [39]:
c.var()

6.666666666666667

Exercise 4 - Print out the shape of the array c.

In [40]:
np.shape(c)

(3, 3)

Exercise 5 - Transpose c and print out transposed result.

In [41]:
print(np.transpose(c))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Exercise 6 - Get the dot product of the array c with c.

In [42]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261.

In [141]:
(c*c.T).sum()

261

Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [43]:
np.product(c*c.T)

131681894400

### Setup 4

In [54]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)
type(d)

numpy.ndarray

Exercise 1 - Find the sine of all the numbers in d.

In [55]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

Exercise 2 - Find the cosine of all the numbers in d.

In [56]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

Exercise 3 - Find the tangent of all the numbers in d.

In [57]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

Exercise 4 - Find all the negative numbers in d.

In [58]:
d[d < 0]

array([-90, -30, -45, -45])

Exercise 5 - Find all the positive numbers in d.

In [59]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

Exercise 6 - Return an array of only the unique numbers in d.

In [64]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

Exercise 7 - Determine how many unique numbers there are in d.

In [65]:
np.unique(d).size

11

Exercise 8 - Print out the shape of d.

In [66]:
d.shape

(3, 6)

Exercise 9 - Transpose and then print out the shape of d.

In [68]:
print(d.T.shape)

(6, 3)


Exercise 10 - Reshape d into an array of 9 x 2.

In [69]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])